/*
  # Create eeat_scores table

  ## Summary
  Stores E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) analysis
  results for each page, generated by AI after page creation.

  ## New Tables
  - `eeat_scores`
    - `id` (uuid, primary key)
    - `page_id` (uuid, FK to pages, cascade delete)
    - `overall_score` (integer 0-100)
    - `experience_score` (integer 0-25)
    - `expertise_score` (integer 0-25)
    - `authoritativeness_score` (integer 0-25)
    - `trustworthiness_score` (integer 0-25)
    - `strengths` (text array, top 3 strengths)
    - `weaknesses` (text array, top 3 weaknesses)
    - `missing_signals` (text array, missing trust/credibility signals)
    - `improvements` (text array, 3 exact improvements)
    - `analyzed_at` (timestamp)

  ## Security
  - RLS enabled
  - Authenticated users can read, insert, and update all scores
*/

CREATE TABLE IF NOT EXISTS eeat_scores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  page_id uuid NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  overall_score integer,
  experience_score integer,
  expertise_score integer,
  authoritativeness_score integer,
  trustworthiness_score integer,
  strengths text[] DEFAULT '{}',
  weaknesses text[] DEFAULT '{}',
  missing_signals text[] DEFAULT '{}',
  improvements text[] DEFAULT '{}',
  analyzed_at timestamptz DEFAULT now(),
  UNIQUE(page_id)
);

ALTER TABLE eeat_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read eeat scores"
  ON eeat_scores FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert eeat scores"
  ON eeat_scores FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update eeat scores"
  ON eeat_scores FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_eeat_scores_page_id ON eeat_scores(page_id);
